[package]
name = "hello_world_cargo"
version = "0.1.0"
edition = "2018"
author = ["Ashish Shrestha"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
